apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare
  namespace: default
spec:
  schedule: 0 * * * *
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 30
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: ddns
            image: afoninsky/cloudflare-ddns
            env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: CLOUDFLARE_API_TOKEN
            - name: CLOUDFLARE_ZONE
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: CLOUDFLARE_ZONE
          restartPolicy: OnFailure