apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

secretGenerator:
  - name: cloudflare
    type: Opaque
    envs: [".env"]
    options:
      disableNameSuffixHash: true

resources:
  - job.yaml