# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: api
build:
  artifacts:
  - image: afoninsky/cloudflare-ddns
    # custom:
    #   buildCommand: sh scripts/buildx.sh
deploy:
  kubectl:
    manifests:
      - job.yaml