# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: api
build:
  artifacts:
  - image: docker.jfrog.booking.com/projects/bplatform-infrastructure/bks-meta-container
    custom:
      buildCommand: sh scripts/buildx.sh
deploy:
  kustomize:
    paths:
      - ./deploy